/**************************************************************/
/****** Author 	: Mayar Saber 							 ******/
/****** SW		: Login System to control Fan and Lights ******/
/****** SWC		: ATMEGA32 - DIO_config.h 			     ******/
/****** Version : 01		 							 ******/
/**************************************************************/
#ifndef		_DIO_CONFIG_H
#define		_DIO_CONFIG_H

/** Initial Directions for all pins */
/** Options: 
			(1) DIO_u8_INITIAL_INPUT
			(2) DIO_u8_INITIAL_OUTPUT
**/
	
/**PORTA**/
#define 	DIO_u8_PA0_INITIAL_DIRECTION	 DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PA1_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PA2_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PA3_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PA4_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PA5_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PA6_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PA7_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT

/**PORTB**/
#define 	DIO_u8_PB0_INITIAL_DIRECTION	 DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PB1_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PB2_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PB3_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PB4_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PB5_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PB6_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PB7_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT

/**PORTC**/
#define 	DIO_u8_PC0_INITIAL_DIRECTION	 DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PC1_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PC2_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PC3_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PC4_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PC5_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PC6_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PC7_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT

/**PORTD**/
#define 	DIO_u8_PD0_INITIAL_DIRECTION	 DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PD1_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PD2_INITIAL_DIRECTION     DIO_u8_INITIAL_INPUT
#define 	DIO_u8_PD3_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PD4_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PD5_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PD6_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT
#define 	DIO_u8_PD7_INITIAL_DIRECTION     DIO_u8_INITIAL_OUTPUT

/***************************************************************/
/** Initial Values for all pins */
/** Options: 
			(1) DIO_u8_INITIAL_INPUT_FLOATING
			(2) DIO_u8_INITIAL_INPUT_PULLUP
			(1) DIO_u8_INITIAL_OUTPUT_LOW
			(2) DIO_u8_INITIAL_OUTPUT_HIGH
**/

/**PORTA**/
#define 	DIO_u8_PA0_INITIAL_VALUE	 DIO_u8_INITIAL_INPUT_FLOATING        //ADC-Temp   (LM35)
#define 	DIO_u8_PA1_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_FLOATING        //ADC-Lights (LDR)
#define 	DIO_u8_PA2_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_FLOATING
#define 	DIO_u8_PA3_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_FLOATING
#define 	DIO_u8_PA4_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW			  //LEDS
#define 	DIO_u8_PA5_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW            //LEDS
#define 	DIO_u8_PA6_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW            //LEDS
#define 	DIO_u8_PA7_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW            //LEDS

/**PORTB**/
#define 	DIO_u8_PB0_INITIAL_VALUE	 DIO_u8_INITIAL_INPUT_FLOATING
#define 	DIO_u8_PB1_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_FLOATING
#define 	DIO_u8_PB2_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_FLOATING
#define 	DIO_u8_PB3_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_HIGH			 //PWM-TIMER0-Non-Inverting
#define 	DIO_u8_PB4_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_PULLUP		 //KPD-c0
#define 	DIO_u8_PB5_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_PULLUP         //KPD-c1
#define 	DIO_u8_PB6_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_PULLUP         //KPD-c2
#define 	DIO_u8_PB7_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_PULLUP         //KPD-c3

/**PORTC**/
#define 	DIO_u8_PC0_INITIAL_VALUE	 DIO_u8_INITIAL_OUTPUT_LOW           //LCD_DataPins
#define 	DIO_u8_PC1_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_DataPins
#define 	DIO_u8_PC2_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_DataPins
#define 	DIO_u8_PC3_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_DataPins
#define 	DIO_u8_PC4_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_DataPins
#define 	DIO_u8_PC5_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_DataPins
#define 	DIO_u8_PC6_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_DataPins
#define 	DIO_u8_PC7_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_DataPins

/**PORTD**/
#define 	DIO_u8_PD0_INITIAL_VALUE	 DIO_u8_INITIAL_OUTPUT_HIGH			 //KPD-r0
#define 	DIO_u8_PD1_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_HIGH			 //KPD-r1
#define 	DIO_u8_PD2_INITIAL_VALUE     DIO_u8_INITIAL_INPUT_PULLUP
#define 	DIO_u8_PD3_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_HIGH			 //KPD-r2
#define 	DIO_u8_PD4_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_HIGH			 //KPD-r3
#define 	DIO_u8_PD5_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW			 //LCD_ControlPins
#define 	DIO_u8_PD6_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_ControlPins
#define 	DIO_u8_PD7_INITIAL_VALUE     DIO_u8_INITIAL_OUTPUT_LOW           //LCD_ControlPins

#endif
